version: '2.1'
orbs:
  nx: nrwl/nx@1.6.1
jobs:
  build:
    docker:
      - image: 'cimg/node:14.17-browsers'
    environment:
      MAIN_BRANCH_NAME: main
      NX_HEAD: origin/main
    steps:
      - checkout
      - run:
          command: npm install
          name: Install dependencies
      - nx/set-shas:
          allow-on-hold-workflow: true
          error-on-no-successful-workflow: true
          main-branch-name: main
          workflow-name: nx-pipeline
      - run:
          command: npx nx run-many --targets=build --all
          name: Run Builds
workflows: null
