version: 2.1

orbs:
  nx: nrwl/nx@1.5.1
  docker: circleci/docker@1.7.0

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: npm ci
      - run:
          name: Get list of affected apps
          command: echo 'export AFFECTED_APPS=$(npx nx print-affected --base=$NX_BASE --head=$NX_HEAD --select=projects)' >> $BASH_ENV
          when: always
      
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --configuration=ci
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
      
      - run:
          name: Dockerize and deploy affected apps
          command: |
            source $BASH_ENV
            if [ -n "$AFFECTED_APPS" ]; then
              for app in $(echo $AFFECTED_APPS | sed "s/,/ /g")
              do
                echo "Dockerizing $app"
                mkdir -p docker/$app/dist/apps
                cp -R dist/apps/$app docker/$app/dist/apps
                cp package.json docker/$app/
                cp apps/$app/Dockerfile docker/$app/
                docker build -t kalyan11021980/$app:latest docker/$app
                echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                docker push kalyan11021980/$app:latest
              done
            fi
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_deploy
