version: 2.1

orbs:
  node: circleci/node@4.1
  docker: circleci/docker@1.7

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npx nx affected:build --base=origin/main
            - run: npx nx affected:test --base=origin/main

  dockerize:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Dockerize
          command: |
            for app in $(nx affected --target=build --base=origin/main --select=apps --prod); do
              docker build -t my-registry/$app .
              docker push my-registry/$app
            done

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build
