version: '2.1'
orbs:
  nx: nrwl/nx@1.6.1
jobs:
  build:
    docker:
      - image: 'cimg/node:14.17-browsers'
    environment:
      MAIN_BRANCH_NAME: main
    steps:
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas:
          allow-on-hold-workflow: true
          error-on-no-successful-workflow: true
          main-branch-name: master
          workflow-name: nx-pipeline
      - run:
          command: yarn nx affected --target=build --base=$NX_BASE
          name: Run Builds
      - run:
          command: yarn nx affected --target=test --base=$NX_BASE
          name: Run Unit Tests
workflows: null